/**
 * Generates public/sitemap.xml and public/robots.txt from the app's public URL inventory.
 * Run: npm run seo:generate
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
  buildPublicUrlInventory,
  CANONICAL_HOST,
  getSitemapChangefreq,
  getSitemapPriority,
  ROBOTS_DISALLOW_PATHS,
} from "../src/lib/seo/publicUrlInventory";
function todayUtc(): string {
  return new Date().toISOString().slice(0, 10);
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function renderSitemap(urls: string[], lastmod: string): string {
  const entries = urls
    .map((loc) => {
      const path = new URL(loc).pathname || "/";
      const changefreq = getSitemapChangefreq(path);
      const priority = getSitemapPriority(path).toFixed(2);
      return `  <url>
    <loc>${escapeXml(loc)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
`;
}

function renderRobots(): string {
  const disallowLines = ROBOTS_DISALLOW_PATHS.map(
    (path) => `Disallow: ${path}`
  ).join("\n");

  return `# Generated by scripts/generate-seo.ts  -  do not edit by hand
User-agent: *
Allow: /

${disallowLines}

Sitemap: ${CANONICAL_HOST}/sitemap.xml
`;
}
async function main() {
  const inventory = buildPublicUrlInventory();
  const lastmod = todayUtc();
  const publicDir = join(process.cwd(), "public");

  await mkdir(publicDir, { recursive: true });

  const sitemapPath = join(publicDir, "sitemap.xml");
  const robotsPath = join(publicDir, "robots.txt");

  await writeFile(sitemapPath, renderSitemap(inventory.allUrls, lastmod), "utf8");
  await writeFile(robotsPath, renderRobots(), "utf8");

  console.log(`Wrote ${sitemapPath} (${inventory.allUrls.length} URLs)`);
  console.log(`Wrote ${robotsPath}`);
  console.log(`Canonical host: ${CANONICAL_HOST}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
